### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by maionaise**
Modification for MQTT port, see Lupusec2Mqtt commit

### CODE REVIEW

**Comment by CyberDNS** [comment]
Hi maionaise,

Thanks for the contribution. 
It took a little time to merge the pull request because family and friends were hit by the flood in West Germany and Luxembourg.

I integrated your changes into the Edge version so that you can test them on the nuki device.
Am I right that Nuki is a Smart door lock?

Best regards,
David

**Comment by maionaise** [comment]
Yes, exactly. I test with NUKI SMART LOCK 2.0

**Comment by CyberDNS** [comment]
What do you think about it to integrate it over Lock integration?

[https://www.home-assistant.io/integrations/lock.mqtt/](https://www.home-assistant.io/integrations/lock.mqtt/)

**Comment by maionaise** [comment]
Yes, makes more sense than a switch with on/off

**Pull request merged**
